server:
  port: 8082
spring:
  application:
    name: auth-service
  redis:
    host: lg-redis
eureka:
  client:
    service-url:
      defaultZone: http://lg-registry:10086/eureka
logging:
  level:
    com.legou: debug
lg:
  oss:
    accessKeyId:
    accessKeySecret:
    host: http://guanda-legou.oss-cn-shanghai.aliyuncs.com
    # 访问oss的bucket的域名
    endpoint: oss-cn-shanghai.aliyuncs.com # 你选择的oss服务器的地址
    dir: "legou-manage" # 保存到bucket的某个子目录
    expireTime: 1200000 # 过期时间，单位是ms
    maxFileSize: 5242880 #文件大小限制，这里是5M
  jwt:
    pubKeyPath: D:/Tools/ssh/id_rsa.pub # 公钥地址
    priKeyPath: D:/Tools/ssh/id_rsa.prv # 私钥地址