server:
  port: 8085
spring:
  application:
    name: sms-service
  rabbitmq:
    host: my_rabbitmq
    username: root
    password: root
    virtual-host: /legou
eureka:
  client:
    service-url:
      defaultZone: http://lg-registry:10086/eureka
logging:
  level:
    com.legou: debug
lg:
  sms:
    accessKeyID:    # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: legou商城 # 签名名称
    verifyCodeTemplate: SMS_191766382 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSms # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id