server:
  port: 10086
spring:
  application:
    name: lg-registry
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://lg-registry:10086/eureka