server:
  port: 8084
spring:
  application:
    name: page-service
  redis:
    host: lg-redis
eureka:
  client:
    service-url:
      defaultZone: http://lg-registry:10086/eureka
logging:
  level:
    # top.javatool.canal: warn # 关闭心跳日志
    com.legou: debug
canal:
  destination: test
  server: lg-canal:11111 # canal地址